development:
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>

staging:
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>

production:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
